package com.kareebo.contacts.dataStructures.common;

/**
 * Base class for representing a client
 */
public class Client extends UserAgent
{
	/**
	 * The client id
	 */
	final private Id id;

	/**
	 * @param platform Information about the OS, it is generated by the client's system
	 * @param version  The version of the client
	 * @param id       The client id
	 */
	public Client(final String platform,final String version,final Id id)
	{
		super(platform,version);
		this.id=id;
	}

	/**
	 * @return The client id
	 */
	public Id getId()
	{
		return id;
	}
}
