package com.kareebo.contacts.dataStructures.common;

/**
 * Information about the user agent, such as platform and version
 */
public class UserAgent
{
	/**
	 * Information about the OS, it is generated by the client's system
	 */
	private final String platform;
	/**
	 * The version of the client
	 */
	private final String version;

	/**
	 * @param platform Information about the OS, it is generated by the client's system
	 * @param version  The version of the client
	 */
	public UserAgent(final String platform,final String version)
	{
		if(platform==null)
		{
			throw new IllegalArgumentException("Platform cannot be null");
		}
		if(version==null)
		{
			throw new IllegalArgumentException("Version cannot be null");
		}
		this.platform=platform;
		this.version=version;
	}

	/**
	 * @return Information about the OS, it is generated by the client's system
	 */
	public String getPlatform()
	{
		return platform;
	}

	/**
	 * @return The version of the client
	 */
	public String getVersion()
	{
		return version;
	}
}
